### ISSUE TITLE
Bad lengths are returned by C13InlineeLineIterator

### ISSUE THREAD

**Issue by jrmuizel** [willglynn/pdb#78]
Currently lengths are calculated by `self.code_offset.offset - self.code_offset_base` unless there's a `ChangeCodeLength`. However code_offset_base doesn't change unless there's a `ChangeCodeOffsetBase` which doesn't seem to be emitted in the wild. Instead, the length should be calculated by subtracting the last code offset.

cc: @jan-auer

**Comment by jan-auer** [comment]
@jrmuizel Could you share a test case where this yields wrong lengths? 

This indeed looks like completely broken math. When implementing this initially, I looked at other open-source implementations that all seemed to interpret the information similar to what ended up in this implementation. Since some of these opcodes are emitted very rarely, I was partially flying blind with this.

A potential fix is in #81, but I haven't checked for examples to verify this. I'd greatly appreciate if you have a reference test for this. Along the lines of this test:

https://github.com/willglynn/pdb/blob/7176d3733a7cefce43e48ad634f387d82f38494a/src/modi/c13.rs#L1453-L1459

**Comment by jrmuizel** [comment]
The test case that I was using with a 1GB xul.pdb I'll try to come up with something smaller.

**Comment by mstange** [comment]
Here's the original testcase:

 1. Download https://symbols.mozilla.org/xul.pdb/5DCA9FFE1E8BC7FE4C4C44205044422E1/xul.pd_
 2. Rename it to `xul.pdb.cab`
 3. Uncompress it.
 4. Look up address `0x4540a80`

The resulting stack should contain both `webrender::frame_builder::FrameBuilder::build` (the outer function) and at least something with `build_layer_screen_rects_and_cull_layers` in it, possibly more.

**Comment by jan-auer** [comment]
Thanks, I'll see if I can extract the binary annotations of one of those functions!
